//! Support items referenced by code generated by `#[tool]` / `#[agent_test]`.
//! Not a stable API.

pub use crate::caps::{Capability, Observations};
pub use crate::testing;
pub use agent_proto;
pub use agent_runtime;
pub use async_trait;
pub use schemars;
pub use serde;
pub use serde_json;
pub use tokio;

use agent_proto::EffectClass;
use agent_runtime::{ToolError, ToolOutput};
use serde_json::{Map, Value};
use tokio_util::sync::CancellationToken;

pub fn schema_generator() -> schemars::gen::SchemaGenerator {
    schemars::gen::SchemaSettings::draft07()
        .with(|s| {
            s.inline_subschemas = true;
            s.option_add_null_type = false;
        })
        .into_generator()
}

pub fn schema_for<T: schemars::JsonSchema>(gen: &mut schemars::gen::SchemaGenerator) -> Value {
    let schema = gen.subschema_for::<T>();
    serde_json::to_value(schema).unwrap_or_else(|_| Value::Object(Map::new()))
}

pub fn object_schema(props: Map<String, Value>, required: &[&str]) -> Value {
    let mut o = Map::new();
    o.insert("type".into(), Value::String("object".into()));
    o.insert("properties".into(), Value::Object(props));
    o.insert(
        "required".into(),
        Value::Array(
            required
                .iter()
                .map(|r| Value::String((*r).into()))
                .collect(),
        ),
    );
    o.insert("additionalProperties".into(), Value::Bool(false));
    Value::Object(o)
}

pub const fn max_class(classes: &[EffectClass]) -> EffectClass {
    let mut best = EffectClass::Pure;
    let mut i = 0;
    while i < classes.len() {
        if classes[i] as u8 > best as u8 {
            best = classes[i];
        }
        i += 1;
    }
    best
}

pub fn parse_args<T: serde::de::DeserializeOwned>(input: Value) -> Result<T, ToolError> {
    // Models sometimes send `null` for a tool without arguments.
    let input = if input.is_null() {
        Value::Object(Map::new())
    } else {
        input
    };
    serde_json::from_value(input).map_err(|e| ToolError::InvalidInput(e.to_string()))
}

pub async fn with_cancel<F: std::future::Future>(
    cancel: &CancellationToken,
    fut: F,
) -> Result<F::Output, ToolError> {
    tokio::select! {
        biased;
        _ = cancel.cancelled() => Err(ToolError::Cancelled),
        v = fut => Ok(v),
    }
}

/// Errors a tool body may return.
pub trait IntoToolError {
    fn into_tool_error(self) -> ToolError;
}
impl IntoToolError for ToolError {
    fn into_tool_error(self) -> ToolError {
        self
    }
}
impl IntoToolError for String {
    fn into_tool_error(self) -> ToolError {
        ToolError::Failed(self)
    }
}
impl IntoToolError for &str {
    fn into_tool_error(self) -> ToolError {
        ToolError::Failed(self.to_string())
    }
}
impl IntoToolError for std::io::Error {
    fn into_tool_error(self) -> ToolError {
        ToolError::Failed(self.to_string())
    }
}
impl IntoToolError for serde_json::Error {
    fn into_tool_error(self) -> ToolError {
        ToolError::Failed(self.to_string())
    }
}
impl IntoToolError for anyhow::Error {
    fn into_tool_error(self) -> ToolError {
        match self.downcast::<ToolError>() {
            Ok(e) => e,
            Err(e) => ToolError::Failed(format!("{e:#}")),
        }
    }
}
impl IntoToolError for Box<dyn std::error::Error + Send + Sync> {
    fn into_tool_error(self) -> ToolError {
        ToolError::Failed(self.to_string())
    }
}

/// The return type of a tool body.
pub trait ToolReturn {
    type Value;
    fn into_tool_result(self) -> Result<Self::Value, ToolError>;
}
impl<T, E: IntoToolError> ToolReturn for Result<T, E> {
    type Value = T;
    fn into_tool_result(self) -> Result<T, ToolError> {
        self.map_err(IntoToolError::into_tool_error)
    }
}

/// Autoref specialisation: specific conversions (`String`, `()`, `ToolOutput`...)
/// win over the generic `Serialize` -> JSON conversion.
pub struct OutWrap<T>(pub T);

pub trait OutputViaSpecific {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError>;
}
impl OutputViaSpecific for OutWrap<String> {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError> {
        Ok(ToolOutput::text(self.0.clone()))
    }
}
impl OutputViaSpecific for OutWrap<&str> {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError> {
        Ok(ToolOutput::text(self.0))
    }
}
impl OutputViaSpecific for OutWrap<()> {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError> {
        Ok(ToolOutput::text("ok"))
    }
}
impl OutputViaSpecific for OutWrap<ToolOutput> {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError> {
        Ok(self.0.clone())
    }
}

pub trait OutputViaSerialize {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError>;
}
impl<T: serde::Serialize> OutputViaSerialize for &OutWrap<T> {
    fn __into_tool_output(&self) -> Result<ToolOutput, ToolError> {
        let value = serde_json::to_value(&self.0).map_err(|e| ToolError::Failed(e.to_string()))?;
        Ok(ToolOutput {
            content: vec![agent_proto::ToolContent::Json { value }],
            ..Default::default()
        })
    }
}
